name: CI pipeline

on: [push]

jobs:
  build:
    name: continuous-integration

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          python-version: 3.12

      - name: Install deps
        run: uv pip install -r requirements.txt

      - name: Run inference
        run: python inference.py
